### ISSUE TITLE
Ejercicios Mapear XML a Clase Java

### ISSUE THREAD

**Issue by Jorgechue10** [Jorgechue10/AccesoDatos#4]
Commit Ejercicio 1 fa37ff2 
Commit Ejercicio 2 16750eb

Ficheros Ejercicio 1:

- [principal](https://github.com/Jorgechue10/AccesoDatos/blob/master/Unidad_01_P07_Mapear_XML_a_clase/operaciones/principal.java)

Ficheros Ejercicio 2:

- [principal_ListaReproduccion](https://github.com/Jorgechue10/AccesoDatos/blob/master/Unidad_01_P07_Mapear_XML_a_clase/operaciones/principal_ListaReproduccion.java)
- [ListaCanciones](https://github.com/Jorgechue10/AccesoDatos/blob/master/Unidad_01_P07_Mapear_XML_a_clase/jaxbClases_ListaReproduccion/ListaCanciones.java)
- [ObjectFactory](https://github.com/Jorgechue10/AccesoDatos/blob/master/Unidad_01_P07_Mapear_XML_a_clase/jaxbClases_ListaReproduccion/ObjectFactory.java)
- [lista_reproduccion.xml](https://github.com/Jorgechue10/AccesoDatos/blob/master/Unidad_01_P07_Mapear_XML_a_clase/lista_reproduccion.xml)
- [lista_reproduccion.xsd](https://github.com/Jorgechue10/AccesoDatos/blob/master/Unidad_01_P07_Mapear_XML_a_clase/lista_reproduccion.xsd)

**Comment by franlu** [comment]
Un ejercicio muy completo :ok_hand:
