### ISSUE TITLE
Práctica

### ISSUE THREAD

**Issue by Jorgechue10** [Jorgechue10/AccesoDatos#5]
Primer comentario: c15c41ee351fc72935824281dd9ec52c161e9a84
Último comentario: fb75ae70c5d4655710a69610eb39df82e72890b0

Fichero:  

-  [AD_3_CrearBD_y_Metodos](https://github.com/Jorgechue10/AccesoDatos/blob/master/Unidad_02_Conectores/P01_MySQL/AD_3_CrearBD_y_Metodos.java)

**Comment by franlu** [comment]
En general, bien. Hubiera quedado mejor separando las clases en ficheros. En los comentarios de los métodos intenta usar los estándares... usa /** + Intro y se crean las etiquetas automáticamente
